name: flutter_init
description: Initialize Flutter Project
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "12.x"
        cache: "gradle"

    - name: Setup Flutter Environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.7.6"
        channel: "stable"
        cache: true

    - name: Get Flutter Dependencies
      shell: bash
      run: flutter pub get

    - name: Generate Internalization
      shell: bash
      run: flutter gen-l10n
