// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpCmlY200ero8Q8qLllNhbtgkfciqpXI',
    appId: '1:333617492020:web:5ece3c766ab005c7209a61',
    messagingSenderId: '333617492020',
    projectId: 'jopa-2-7ceee',
    authDomain: 'jopa-2-7ceee.firebaseapp.com',
    storageBucket: 'jopa-2-7ceee.appspot.com',
    measurementId: 'G-970S039H2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZ1l_93KZ5Stnq4e-TQLVW6uFC5F1XfQ',
    appId: '1:333617492020:android:0e34dc95bf0ee28e209a61',
    messagingSenderId: '333617492020',
    projectId: 'jopa-2-7ceee',
    storageBucket: 'jopa-2-7ceee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAxTS-Nw9eFaJR_xvpecSOams_RQiMaA',
    appId: '1:333617492020:ios:679420a040624e24209a61',
    messagingSenderId: '333617492020',
    projectId: 'jopa-2-7ceee',
    storageBucket: 'jopa-2-7ceee.appspot.com',
    iosClientId: '333617492020-6fv3c4341f36sitbe4o0e8a0vophpvih.apps.googleusercontent.com',
    iosBundleId: 'com.lim.serverStatus',
  );
}
