// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpM6zBzFrC8tbfLQaOBQr6d1Nx5B610N8',
    appId: '1:110941769754:web:9e3d414948c4068c6501a3',
    messagingSenderId: '110941769754',
    projectId: 'server-status-7a338',
    authDomain: 'server-status-7a338.firebaseapp.com',
    storageBucket: 'server-status-7a338.appspot.com',
    measurementId: 'G-01T7QE1PX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjJ-a1wMXHnxhCSoWwWgiSlCO5Thqw-uw',
    appId: '1:110941769754:android:c75d7795aa2bc4646501a3',
    messagingSenderId: '110941769754',
    projectId: 'server-status-7a338',
    storageBucket: 'server-status-7a338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbHi1MxMgnuUQkb7OgIEaIeufGIZgq5Bg',
    appId: '1:110941769754:ios:a5d560b5ed86b22c6501a3',
    messagingSenderId: '110941769754',
    projectId: 'server-status-7a338',
    storageBucket: 'server-status-7a338.appspot.com',
    iosClientId: '110941769754-1km6f65gbqbh030n2ldb1pirh3qr73m5.apps.googleusercontent.com',
    iosBundleId: 'com.lim.minecraftserverStatus',
  );
}
