name: Android Release

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter init
        uses: ./.github/actions/flutter_init

      - name: Start release build
        run: flutter build apk --release --dart-define=MINECRAFT_SERVER_IP=${{ vars.MINECRAFT_SERVER_IP }}

      - name: Upload Android Build Files
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: ./build/app/outputs/flutter-apk/app-release.apk