name: Android Release

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build apk --release --dart-define=MINECRAFT_SERVER_IP=${{ vars.MINECRAFT_SERVER_IP }}

      - name: Upload Android Build Files
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: ./build/app/outputs/flutter-apk/app-release.apk