name: Web Release

on:
  push:
    branches:  [ "master" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Flutter init
        uses: ./.github/actions/flutter_init

      - name: Start Web Release Build
        run: flutter build web --release --base-href "/minecraft_server_status/" --dart-define=MINECRAFT_SERVER_IP=${{ vars.MINECRAFT_SERVER_IP }}

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: ./build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v3
        with:
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./